/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardsSelector: typeof import('./src/components/CardsSelector.vue')['default']
    GameResult: typeof import('./src/components/GameResult.vue')['default']
    GameResultGrouped: typeof import('./src/components/GameResultGrouped.vue')['default']
    GameSettings: typeof import('./src/components/GameSettings.vue')['default']
    PButton: typeof import('primevue/button')['default']
    PCard: typeof import('primevue/card')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PDivider: typeof import('primevue/divider')['default']
    PDropdown: typeof import('primevue/dropdown')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PokerCard: typeof import('./src/components/PokerCard.vue')['default']
    PokerIcon: typeof import('./src/icons/PokerIcon.vue')['default']
    POverlayPanel: typeof import('primevue/overlaypanel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    ShareDialog: typeof import('./src/components/ShareDialog.vue')['default']
    StackFooter: typeof import('./src/components/StackFooter.vue')['default']
    UserSettings: typeof import('./src/components/UserSettings.vue')['default']
  }
}
